filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

syntax on

" Use Vim settings, rather then Vi settings. This setting must be as early as
" " possible, as it has side effects.
set nocompatible

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
"set ruler         " show the cursor position all the time
"set showcmd       " display incomplete commands
set incsearch     " do incremental searching
"set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set confirm       " Need confrimation while exit
set fileencodings=utf-8,gb18030,gbk,big5

set tabstop=2
set shiftwidth=2
set expandtab
set cindent
set hlsearch

nmap <F5> :NERDTreeToggle<cr>

Bundle 'Valloric/YouCompleteMe'
Bundle 'kien/ctrlp.vim'
Bundle 'vim-scripts/ctags.vim'
Bundle "scrooloose/nerdtree"

